### PR TITLE
Add intercept function + calling in workflows

### PR DESCRIPTION
**Pull request by MOohTus**
- I created a intercept function inside the MOTL_functions.R. 
- I wrote a calling of this function inside TCGA and Glioblastoma workflows. 
- I suggest to remove the intercept script in both workflows

What do you think about this modification @david-hirst?

### CODE REVIEW

**Comment by david-hirst** [comment]
Salut - can you please do the following:

- Use the original directory naming convention (ExpDataDir and FctrznDir)
- Use the directories as the input for the function
- Apply the function in a separate script, not embedded in the TL_VI script. It is a one off task that doesn't need to be repeated each time the TL_VI workflow is run

Thanks!

**Comment by MOohTus** [comment]
It's not ready yet David. I will work on it next week ;)

**Comment by MOohTus** [comment]
Hi! 

- I used the original directory naming convention (`ExpDataDir` and `FctrznDir`)
- Input of the intercept function are now: 
-- `expdat_meta` (metadata of the learning set)
-- `Fctrzn` (factorization results of the learning set)
-- `FctrznDir` (directory of the learning set factorization)
-- `ExpDataDir` (directory of the learning set data)
- The intercept function is calling in the separate script (as you did before). I changed the initial files. 

There is a results checkpoint to compare your file and the file created with the function. Every thing seems ok. Maybe it could be good to run again the workflow from this part. 

What do you think about the modifications @david-hirst?

**Comment by david-hirst** [comment]
Salut @MOohTus 

Thanks for following up on those suggestions. 

It looks good - before I run the function and compare to existing results, I've got a question:

Why do we need to pass `expdat_meta` and `Fctrzn` to the function?

They are loaded using the directories that are passed to the function in the original script:

`expdat_meta = readRDS(file.path(ExpDataDir,'expdat_meta.rds'))`

`InputModel = file.path(FctrznDir,"Model.hdf5")`
`Fctrzn = load_model(file = InputModel)`

Can't we do the same with the function? Pass the directories and it will load the required objects?

Cheers

**Comment by david-hirst** [comment]
Salut @MOohTus, 

I've run the function and it gave me the same results as before - so we can commit these changes.

I'll leave it up to you to decide whether we need to pass `expdat_meta` and `Fctrzn` to the function - I guess the flexibility is good if a user has the objects named differently.

Thanks!

**Comment by MOohTus** [comment]
After discussion, we decided to keep the loading part outside the function for flexibility. 

Thanks for your feedback @david-hirst! It's great if it gives same results! 

I removed the commented lines in intercept files for Glio and TCGA. And the seed init was already in both scripts. 

:)

**Pull request merged**
